### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by sykxiaoqiang** [LCAV/FRIDA#1]
when I enter “./make_all_figures.sh -t” it shows 
Traceback (most recent call last):
  File "figure_doa_experiment.py", line 105, in <module>
    import doa
  File "/home/syk/FRIDA-master/doa/__init__.py", line 19, in <module>
    import tools_fri_doa_plane as tools_fri
ModuleNotFoundError: No module named 'tools_fri_doa_plane'

can you give me some suggestions to figure it out？thx . My python version is 3.6

**Comment by hanjiepan** [comment]
@fakufaku I think this is probably related to the import in Python 3: 
change `import tools_fri_doa_plane as tools_fri` to `import .tools_fri_doa_plane as tools_fri` should fix it.

**Comment by ebezzam** [comment]
With Python 3, there will be some other problems like `print` statements without parenthesis, such as Line 99 of [`figure_doa_experiment_plot.py`](https://github.com/LCAV/FRIDA/blob/3078869e6b2298c2cf9ea7996fdc42c18eb82cd3/figure_doa_experiment_plot.py#L99).

**Comment by sykxiaoqiang** [comment]
> @fakufaku I think this is probably related to the import in Python 3:
> change `import tools_fri_doa_plane as tools_fri` to `import .tools_fri_doa_plane as tools_fri` should fix it.

thanks,now i use python2.7....

**Comment by sykxiaoqiang** [comment]
> With Python 3, there will be some other problems like `print` statements without parenthesis, such as Line 99 of [`figure_doa_experiment_plot.py`](https://github.com/LCAV/FRIDA/blob/3078869e6b2298c2cf9ea7996fdc42c18eb82cd3/figure_doa_experiment_plot.py#L99).

yes.Changed a lot of code before,now i use python2.7
