### ISSUE TITLE
Hello, can I use the GPU to run the code? Can you give me suggestion?

### ISSUE THREAD

**Issue by sykxiaoqiang** [LCAV/FRIDA#2]
thanks,i want to use MKL,but i use AMD 2700x,so can i  use nvidia cuda to accelerate it.

**Comment by fakufaku** [comment]
Hi @sykxiaoqiang , sorry we don't support directly either mkl or gpu. These are sometimes implicitely used under the hood for numpy and scipy, which we use.
You could try to take a look at `cupy` which maintains a similar api to numpy and allows to offload computations to the GPU. You would need to change some import within the library though.
Which part exactly do you want to make faster ?

**Comment by sykxiaoqiang** [comment]
@fakufaku thanks for your work,i meet a new problem，when i run figure_doa_experiment.py,it will report an error:
Using ipyparallel processing.
Waiting for connection file: ~/.ipython/profile_default/security/ipcontroller-client.json
Traceback (most recent call last):
  File "figure_doa_experiment.py", line 302, in <module>
    c = ip.Client()
  File "/home/syk/anaconda2/lib/python2.7/site-packages/ipyparallel/client/client.py", line 413, in __init__
    raise IOError(msg)
IOError: Connection file '~/.ipython/profile_default/security/ipcontroller-client.json' not found.
You have attempted to connect to an IPython Cluster but no Controller could be found.
Please double-check your configuration and ensure that a cluster is running.

Can you tell me how to solve this problem?
thank u very much

**Comment by sykxiaoqiang** [comment]
@fakufaku thanks for your work. I found the code to run slow because I didn't load ipython in ubuntu and now I solved this problem.

**Comment by fakufaku** [comment]
Great to hear you could solve it!

**Comment by fakufaku** [comment]
Great to hear you could solve it!
